name: Test
title: "Test: "
description: Test description.
labels: ["test"]
body:
  - id: textarea
    type: textarea
    attributes:
      label: Textarea label
      placeholder: textarea placeholder.
